# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: MIPT Test Challenge
short_description: Unittests + Random score generator
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: MIPT Leaderboard
evaluation_script: evaluation_script.zip
remote_evaluation: False
is_docker_based: False
start_date: 2019-01-01 00:00:00
end_date: 2099-05-31 23:59:59
published: True

leaderboard:
  - id: 1
    schema:
      {
        "labels": ["Tests Passed", "Total"],
        "default_order_by": "Total",
        "metadata":
          {
            "Tests Passed":
              {
                "sort_ascending": True,
                "description": "Amount of passed tests",
              },
            "Total":
              {
                "sort_ascending": True,
                "description": "Total score genereted by 'get_basic_score' methode",
              },
          },
      }

challenge_phases:
  - id: 1
    name: MIPT Unit Test
    description: templates/challenge_phase_2_description.html
    leaderboard_public: False
    is_public: True
    is_submission_public: True
    start_date: 2019-01-01 00:00:00
    end_date: 2099-05-24 23:59:59
    test_annotation_file: annotations/data_assignment02.npy
    codename: test
    max_submissions_per_day: 5
    max_submissions_per_month: 50
    max_submissions: 50
    default_submission_meta_attributes:
      - name: FIO
        is_visible: True
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False

dataset_splits:
  - id: 1
    name: Test Split
    codename: test

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 1
    leaderboard_decimal_precision: 1
    is_leaderboard_order_descending: True
